blank_issues_enabled: false
contact_links:
  - name: Ask Pyrofork related questions
    url: https://stackoverflow.com/questions/tagged/pyrofork
    about: This place is only for reporting issues about Pyrofork. You can ask questions at StackOverflow.
  - name: Join the Telegram chat
    url: https://t.me/MayuriChan_Chat
    about: Join the official chat and stay tuned for news, updates and announcements.